server:
  port: 8081

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:

        customer-output:
          destination: ex.customer
          producer:
            requiredGroups:
              - qe.customer
